"""Optional email delivery for scan reports — SMTP over SSL (Hostinger).

Strictly additive to the /report flow: if this fails, the PDF still
downloads normally in the browser. See web/app.py for the fail-open wiring.
"""

from __future__ import annotations

import os
import smtplib
from email.message import EmailMessage

_REQUIRED_ENV_VARS = (
    "NEXUM_SMTP_HOST",
    "NEXUM_SMTP_PORT",
    "NEXUM_SMTP_USER",
    "NEXUM_SMTP_PASSWORD",
    "NEXUM_SMTP_FROM",
)


class EmailDeliveryError(RuntimeError):
    """Raised when the report email cannot be sent."""


def send_report_email(to_address: str, pdf_bytes: bytes, pdf_filename: str) -> None:
    missing = [name for name in _REQUIRED_ENV_VARS if not os.environ.get(name)]
    if missing:
        raise EmailDeliveryError(f"Missing SMTP configuration: {', '.join(missing)}")

    host = os.environ["NEXUM_SMTP_HOST"]
    port = int(os.environ["NEXUM_SMTP_PORT"])
    user = os.environ["NEXUM_SMTP_USER"]
    password = os.environ["NEXUM_SMTP_PASSWORD"]
    sender = os.environ["NEXUM_SMTP_FROM"]

    message = EmailMessage()
    message["Subject"] = "Your Nexum Risk Report"
    message["From"] = sender
    message["To"] = to_address
    message.set_content(
        "Your Nexum Trust & Risk Report is attached.\n\n"
        "Generated by the Nexum Scanner — https://getnexum.dev"
    )
    message.add_attachment(pdf_bytes, maintype="application", subtype="pdf", filename=pdf_filename)

    try:
        with smtplib.SMTP_SSL(host, port, timeout=15) as smtp:
            smtp.login(user, password)
            smtp.send_message(message)
    except (smtplib.SMTPException, OSError) as exc:
        raise EmailDeliveryError(str(exc)) from exc
