"""Optional email delivery for scan reports — Resend HTTPS API.

Strictly additive to the /report flow: if this fails, the PDF still
downloads normally in the browser. See web/app.py for the fail-open wiring.

Switched from SMTP (Hostinger) to Resend because Railway blocks outbound
SMTP on the current plan (Pro-only). getnexum.dev is verified in Resend, so
the sender stays hello@getnexum.dev — the same address the SMTP flow used.
"""

from __future__ import annotations

import base64
import os

import httpx

_RESEND_URL = "https://api.resend.com/emails"
_FROM_ADDRESS = "Nexum <hello@getnexum.dev>"


class EmailDeliveryError(RuntimeError):
    """Raised when the report email cannot be sent."""


def send_report_email(to_address: str, pdf_bytes: bytes, pdf_filename: str) -> None:
    api_key = os.environ.get("RESEND_API_KEY")
    if not api_key:
        raise EmailDeliveryError("Missing RESEND_API_KEY configuration")

    payload = {
        "from": _FROM_ADDRESS,
        "to": [to_address],
        "subject": "Your Nexum Risk Report",
        "text": (
            "Your Nexum Trust & Risk Report is attached.\n\n"
            "Generated by the Nexum Scanner — https://getnexum.dev"
        ),
        "attachments": [
            {
                "filename": pdf_filename,
                "content": base64.b64encode(pdf_bytes).decode("ascii"),
            }
        ],
    }

    try:
        response = httpx.post(
            _RESEND_URL,
            headers={
                "Authorization": f"Bearer {api_key}",
                "Content-Type": "application/json",
            },
            json=payload,
            timeout=15,
        )
    except (httpx.TimeoutException, httpx.HTTPError) as exc:
        raise EmailDeliveryError(str(exc)) from exc

    if response.status_code >= 400:
        raise EmailDeliveryError(f"Resend API error {response.status_code}: {response.text}")
